

development:
  adapter: postgresql
  database: spblog_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: spblog_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: spblog_production
  pool: 5
  timeout: 5000


